version: "3"

services:
  shlink:
    image: shlinkio/shlink:stable
    restart: always
    environment:
      - TZ="America/New_York"
      - DEFAULT_DOMAIN=<DEFAULT_DOMAIN>
      - IS_HTTPS_ENABLED=<true/false>
      - GEOLITE_LICENSE_KEY=<GEOLITE_LICENSE_KEY>
      - DB_DRIVER=maria
      - DB_USER=shlink
      - DB_NAME=shlink
      - DB_PASSWORD=<DB_PASSWORD>
      - DB_HOST=database
    depends_on:
      - database
    ports:
      - 127.0.0.1:<8888>:8080

  database:
    image: mariadb:10.8
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=<MARIADB_ROOT_PASSWORD>
      - MARIADB_DATABASE=shlink
      - MARIADB_USER=shlink
      - MARIADB_PASSWORD=<DB_PASSWORD>
    volumes:
      - /opt/shlink/db_data:/var/lib/mysql
